### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-team-pro-1#2]
[IHome.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-team-pro-1/files/8129668/IHome.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACIÓN: 18/20.

Faltan algunos puntos en la portada, ademas no tienen introducción, descripcion de la practica y objetivo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
