### ISSUE TITLE
PRACITCA  1 RDS

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-team-pro-1#3]
[PRACTICA 1 14-02-2024.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-team-pro-1/files/14284777/PRACTICA.1.14-02-2024.pdf)

**Comment by Luz1727** [comment]
calificacion: 16/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
